# Generated by Django 4.2 on 2024-03-09 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='待补题')),
                ('detail', models.TextField(blank=True, null=True)),
                ('createtime', models.DateTimeField(default=datetime.datetime.now)),
                ('deadtime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('status', models.IntegerField(default=1)),
                ('tag', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
