# Generated by Django 4.2 on 2024-03-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userlogindata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='realname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='des',
        ),
        migrations.AddField(
            model_name='userdata',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
